name:  Matteo Guadrini - Laszlo Suto Nagy
theme: jekyll-theme-minimal
show_downloads: true
description: "Fule-Butterfly Backup is a simple command line wrapper of rsync for complex task, written in python."
